export { TitleBar } from './TitleBar'
export { ActivityBar } from './ActivityBar'
export { Sidebar } from './Sidebar'
export { EditorArea } from './EditorArea'
export { StatusBar } from './StatusBar'
